### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by parames3010** [enarjord/passivbot_futures#3]
Hello i am just a beginner.  I see some interesting functions such as “Borrow / Repay”, is it possible that you add a “Automatically Borrow” when Liq.Price reaches the limit?

**Comment by enarjord** [comment]
hi,

apologies for late response

it is probably possible to automate adding or removing margin in isolated mode yes

it may be easier tho, to simply use cross margin

on binance you set a leverage on both cross and isolated modes

on bybit cross mode leverage is always maximum, 100x in the case of btcusd
