### ISSUE TITLE
Grid_style code: Asks for ddown_factor in settings file

### ISSUE THREAD

**Issue by eugjr** [enarjord/passivbot_futures#5]
Hi.
I'm trying the code for the grid_style, and get an error running it, as it asks the ddown_factor in settings. I"ve created it with the value of 10, and the code works. 
My doubt is if the ddown_factor is really needed for the grid style version, as the code seems to work different than the doubler version.

**Comment by enarjord** [comment]
my bad, i renamed entry_qty_scaling_factor to ddown_factor, and forgot to change it in default settings

ddown_factor is the number by which pos_size is multiplied to get next entry_qty

if you use 10, and pos_size is 14, then next entry will have qty 140

and yes, the grid style works differently compared to the older version

it's still under development

i'm running backtests to find good settings to use.  it works live, but i am still wary to use it

**Comment by enarjord** [comment]
just made an update, binance should work now

there might still be bugs

**Comment by eugjr** [comment]
Thank you for the support. Do you have a telegram account where we can chat?

**Comment by enarjord** [comment]
yes, @enarjord
